Ember.TEMPLATES['navbar'] = Ember.Handlebars.template(function anonymous(Handlebars,depth0,helpers,partials,data) {
this.compilerInfo = [4,'>= 1.0.0'];
helpers = this.merge(helpers, Ember.Handlebars.helpers); data = data || {};
  


  data.buffer.push("<nav role=\"navigation\" class=\"navbar navbar-default navbar-fixed-top\">\n    <div class=\"container\">\n        <div class=\"navbar-header\">\n            <button type=\"buttonin\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\" class=\"navbar-toggle\">\n                <span class=\"sr-only\">Toggle navigation</span>\n                <span class=\"icon-bar\"></span>\n                <span class=\"icon-bar\"></span>\n                <span class=\"icon-bar\"></span>\n            </button>\n            <a href=\"#\" class=\"navbar-brand\">Ember Components</a>\n        </div>\n        <div class=\"collapse navbar-collapse navbar-ex1-collapse\">\n            <ul class=\"nav navbar-nav\">\n                <li class=\"active\">\n                    <a href=\"#\">\n                        <i class=\"fa fa-home\"></i>\n                        Home\n                    </a>\n                </li>\n                <li>\n                    <a href=\"https://github.com/ember-addons/ember-components\">\n                        <i class=\"fa fa-github-alt\"></i>\n                        Github\n                    </a>\n                </li>\n            </ul>\n            <form class=\"navbar-form navbar-right\">\n                <a href=\"https://github.com/ember-addons/ember-components/archive/master.zip\" style=\"font-weight:bold\" class=\"btn btn-success\">\n                    <i class=\"fa fa-save\"></i>\n                    Download 1~ kb\n                </a>\n            </form>\n            <div class=\"socials\" style=\"text-align: center\">\n                <ul class=\"bs-social-buttons\">\n                    <li>\n                        <!-- github -->\n                        <div>\n                        <iframe class=\"github-btn\"\n                            src=\"http://ghbtns.com/github-btn.html?user=ember-addons&amp;repo=ember-components&amp;type=watch&amp;count=true\" width=\"100\" height=\"20\" title=\"Star on GitHub\"></iframe>\n                        </div>\n                    </li>\n                </ul>\n            </div>\n        </div>\n    </div>\n</nav>\n\n");
  
});
